Publish on Fleek Github workflow
aragon/developer-portal pull request #135
Opened 2023-11-23 19:36 UTC by chilcano

## Description

* Adds Github workflow to publish content on Fleek based on branch.
* Adds Fleek API Key as secret
* Adds Fleek configuration

Task: [DOPS-595](https://aragonassociation.atlassian.net/browse/DOPS-595)

[DOPS-595]: https://aragonassociation.atlassian.net/browse/DOPS-595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-11-24 08:20 UTC, Michael-A-Heuer commented
Is this really needed? See the discussion on discord: https://discord.com/channels/672466989217873929/1176842352044814408/1177333413213126737

2023-11-24 08:21 UTC, Michael-A-Heuer requested changes
Is this really needed? See the discussion on discord: https://discord.com/channels/672466989217873929/1176842352044814408/1177333413213126737

2023-11-27 11:13 UTC, Michael-A-Heuer commented on .github/workflows/publish-on-fleek.yaml
> +      - name: Get Fleek outpu URL ( Branch=${{ inputs.source_branch }} )
```suggestion
      - name: Get Fleek output URL ( Branch=${{ inputs.source_branch }} )
```

2023-11-27 11:25 UTC, Rekard0 commented on fleek_master.json
> +}
add empty line at the the end

2023-11-27 11:25 UTC, Rekard0 commented on fleek_staging.json
> +}
add empty line at the the end

2023-11-30 12:52 UTC, Michael-A-Heuer approved these changes

2023-11-30 14:54 UTC, merged