Chore: Add DAO Docs
aragon/developer-portal pull request #184
Opened 2024-05-29 07:45 UTC by josemarinas

Add DAO docs.

Links need revisit once all docs are in place

2024-05-30 07:59 UTC, banasa44 requested changes

2024-05-30 07:59 UTC, banasa44 commented on docs/advanced/dao/00-introduction.md
> +note
```suggestion
:::note
```

2024-05-30 07:59 UTC, banasa44 commented on docs/advanced/dao/00-introduction.md
> +
```suggestion
:::

```

2024-05-30 07:59 UTC, banasa44 commented on docs/advanced/dao/01-creation.md
According to the Notion page, we should talk about events emitted.
Same with the granted/revoked permissions, maybe we should be more explicit in the 4 steps for creating a DAO?
(becomes initial owner = ROOT?, when revoked then granted to the DAO?).
Maybe a diagram of the framework would be nice? I split the diagram
https://devs.aragon.org/assets/images/aragon-os-infrastructure-core-overview.drawio-a18dc7490bee8079650bff8e44a124dd.svg
For the plugin framework section... maybe you could take the other side?

2024-05-30 10:13 UTC, josemarinas commented on docs/advanced/dao/01-creation.md
Yes I wanted to talk about events but since the plugin installation events are emmited by the PSP and not the DAO itself i wasnt sure that it was the rigth place but maybe mentioning them is no harm.

I'll add more info for the dao steps and the half diagram

2024-06-03 08:20 UTC, banasa44 commented on docs/advanced/dao/01-creation.md
> +![Creation Schema](/img/advanced/dao/aragon-osx-dao-creation.drawio.svg)
```suggestion
![Creation Schema](/optimized-svg/advanced/dao/aragon-osx-dao-creation.drawio.svg)
```

2024-06-03 08:20 UTC, banasa44 commented on docs/advanced/dao/01-creation.md
> +- [`TokenVoting`](https://link-to-more-info/)
Maybe we can come again to this comment when we merge other docs, but I created a dedicated section for governance plugins, maybe could point to it.

2024-06-03 08:20 UTC, banasa44 commented on docs/advanced/dao/01-creation.md
> +When creating a DAO there is 2 main events that you'll be looking for:
```suggestion
When creating a DAO there is two main events that you'll be looking for:
```

2024-06-03 10:37 UTC, banasa44 commented
Consider adding DAO advanced actions sections right after the intro.

2024-06-07 11:19 UTC, clauBv23 commented
wait for #192 to merge this one

2024-06-20 13:02 UTC, Rekard0 approved these changes

2024-06-20 13:10 UTC, merged